title: مقالات من
description: یادداشت‌هایی درباره هوش مصنوعی، مهندسی نرم‌افزار و داده
lang: fa
author: امین توکلی

markdown: kramdown
highlighter: rouge

permalink: /articles/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post